const days=[
['Fundamentos de seguridad','Activos, amenazas, riesgos y la tríada CIA','Security Basics'],['Requisitos y diseño seguro','SSDLC, mínimo privilegio y defensa en profundidad','Secure Design Principles'],['Reutilización segura','Dependencias, SCA, SBOM y software de terceros','Reusing External Software'],['Validación de entradas','Inyecciones, JSON, normalización y ReDoS','Input Validation'],['Procesamiento seguro de datos','Memoria, identidad, sesiones y seguridad web','Processing Data Securely'],['Comandos y archivos','Shell, rutas, permisos, TLS y firmas','Calling Other Programs'],['Salidas, errores y logs','XSS, excepciones, telemetría y privacidad','Sending Output'],['Verificación y pruebas','SAST, DAST, fuzzing y regresión','Verification'],['Threat Modeling','DFD, fronteras de confianza y STRIDE','Threat Modeling'],['Criptografía y examen final','Hashes, cifrado, claves, firmas y despliegue','Other Topics']
];
const topics=[
  [
    ["What best represents an asset in security?",["A valued resource requiring security protection","A weakness that could expose a valued resource","An event that could harm a business resource","A safeguard that reduces exposure to threats"],0,"Un activo puede ser información, software, hardware, una identidad o cualquier recurso con valor para la organización. Su valor justifica los controles de protección."],
    ["¿Qué describe el riesgo?",["La probabilidad y el impacto de un escenario de amenaza","La gravedad técnica de una debilidad descubierta","La frecuencia de intentos contra un servicio","El coste previsto de implantar una mitigación"],0,"El riesgo se estima considerando la probabilidad de que ocurra un evento y el impacto que tendría. Su importancia depende del impacto y contexto."],
    ["What does confidentiality protect?",["Preventing unauthorized disclosure of information","Preventing unauthorized modification of information","Maintaining timely access to needed information","Providing verifiable evidence of the original data source"],0,"La confidencialidad limita el acceso a quienes tienen autorización. Un permiso delimita la lectura legítima."],
    ["¿Cuál es un ejemplo de pérdida de integridad?",["Un registro modificado por alguien sin permiso","Un registro legítimo divulgado a un tercero ajeno","Un registro temporalmente inaccesible a su dueño","Un registro aprobado sin conservar su autoría"],0,"La integridad exige que los datos sean exactos y no sufran modificaciones indebidas. Un cambio puede invalidar el significado original."],
    ["What does availability provide?",["Timely and reliable access to required systems and data","Reliable evidence of who changed system data","Controlled access to sensitive system contents","Protection against unauthorized changes to data"],0,"La disponibilidad se ocupa del acceso oportuno y confiable a servicios y datos. La continuidad exige recursos y recuperación efectiva."],
    ["¿Qué significa no repudio?",["Aportar evidencia que dificulte negar una acción propia","Comprobar la identidad antes de permitir una operación","Impedir que terceros ajenos lean el contenido de una operación","Detectar alteraciones en los datos de una operación"],0,"Firmas, registros confiables y controles de identidad pueden aportar evidencia de una acción. La evidencia protegida permite atribuir acciones verificables."],
    ["When inventorying critical assets, what should be recorded first?",["Owner, value, dependencies and business impact of its loss","Hostname, hardware model, software version and location","Open ports, network routes, firewall rules and protocols","Known flaws, exploit examples, patches and scan results"],0,"El contexto del activo permite priorizar controles con base en el impacto real. El contexto permite priorizar qué proteger primero."],
    ["¿Qué diferencia una amenaza de una vulnerabilidad?",["La amenaza puede causar daño; la vulnerabilidad facilita que ocurra","La amenaza es la debilidad técnica; la vulnerabilidad es quien la aprovecha","La amenaza es el impacto sufrido; la vulnerabilidad es su frecuencia","La amenaza es el riesgo residual; la vulnerabilidad es el control"],0,"Una amenaza puede aprovechar una vulnerabilidad para producir un impacto. La debilidad facilita materializar una amenaza."],
    ["What is the purpose of authenticity?",["Verifying that a claimed identity or data source is genuine","Verifying that an entity may perform a given action","Verifying that received data remains available to users","Verifying that an operation cannot later be denied"],0,"La autenticidad ayuda a confiar en el origen o identidad de una entidad. La identidad del origen requiere verificación adicional."],
    ["¿Por qué clasificar activos?",["Para ajustar controles a la sensibilidad y al valor del activo","Para ordenar controles según la fecha de compra del activo","Para distribuir controles según la marca del equipo usado","Para elegir controles según el número de usuarios del área"],0,"La clasificación orienta decisiones proporcionales de protección, retención y acceso. El impacto determina la protección necesaria."]
  ],
  [
    ["What are security requirements?",["Testable security conditions addressing identified system risks","General security goals without measurable acceptance criteria","Implementation suggestions left to individual developer choice","Operational targets concerned with response time and capacity"],0,"Deben expresarse de forma verificable, por ejemplo: “el sistema bloqueará la sesión tras N intentos”. Las pruebas permiten demostrar su cumplimiento."],
    ["¿Cuándo debe comenzar el SSDLC?",["Al definir necesidades y diseñar el producto","Al estabilizar la primera versión funcional","Al preparar una revisión previa al despliegue inicial","Al iniciar la evaluación externa del producto"],0,"Incorporar seguridad temprano reduce el coste de corregir defectos y permite decisiones de arquitectura informadas. Cada fase introduce o reduce riesgos."],
    ["What does least privilege mean?",["Granting only permissions required for the assigned function","Granting the permissions usually held by the same team","Granting temporary administrator access for routine work","Granting the permissions available to the service owner"],0,"Limitar privilegios reduce el alcance de una explotación o de un error. Menos capacidades limitan daños tras un compromiso."],
    ["¿Qué es defensa en profundidad?",["Combinar barreras que contengan el fallo de otra capa","Repetir el mismo control con las mismas dependencias","Concentrar los controles en la frontera externa de red","Sustituir controles internos por un filtro en el perímetro de red"],0,"Varias capas reducen la posibilidad de que un fallo único comprometa todo el sistema. Las barreras adicionales pueden contener un fallo."],
    ["What does “secure by default” mean?",["Starting with restrictive settings appropriate to the use case","Starting with broad access until permissions are reviewed","Starting with settings copied from the testing environment","Starting with optional controls awaiting user activation"],0,"Los valores predeterminados no deberían dejar expuesto al usuario que no cambió la configuración. Reduce exposición antes de personalizar la configuración."],
    ["¿Qué es la mediación completa?",["Comprobar autorización en todo acceso al recurso protegido","Comprobar la autorización al crear la sesión inicial","Comprobar el rol al mostrar las funciones del cliente","Comprobar permisos al generar enlaces a los recursos"],0,"Cada solicitud debe pasar por el control de autorización correspondiente. Los permisos cambian entre solicitudes sucesivas."],
    ["What does open design propose?",["Protection holds even when the mechanism design is public","Protection relies on concealing how the mechanism works","Protection relies on changing the mechanism after disclosure","Protection relies on limiting design reviews to its authors"],0,"La seguridad debería resistir el análisis público; los secretos deben estar en las claves, no en el diseño. La revisión pública revela supuestos incorrectos."],
    ["¿Cuál reduce la superficie de ataque?",["Retirar funciones, servicios y dependencias no requeridos","Mover servicios innecesarios a otro puerto disponible","Renombrar las rutas de administración expuestas al público","Ocultar la versión de los paquetes que siguen instalados"],0,"Menos funcionalidad expuesta implica menos oportunidades de abuso. Los componentes innecesarios pueden contener defectos explotables."],
    ["What should a security acceptance criterion contain?",["An observable security outcome with a measurable pass rule","A statement of intent with a general security objective","A planned activity with the name of its responsible owner","A preferred technology with an estimated adoption and rollout deadline"],0,"Los criterios concretos permiten probar y demostrar que el requisito se cumple. Una condición medible permite verificar su cumplimiento."],
    ["¿Qué es una decisión de seguridad de arquitectura?",["Elegir los límites de confianza y mecanismos de aislamiento","Elegir el orden de archivos dentro del repositorio fuente","Elegir nombres de variables para los controles existentes","Elegir el formato de comentarios de los módulos desplegados del sistema"],0,"Separar servicios, elegir un mecanismo de identidad o definir flujos de datos son decisiones arquitectónicas. La estructura condiciona la propagación de fallos."]
  ],
  [
    ["What is a transitive dependency?",["A component required by another dependency of the project","A component explicitly required by the project itself","A component supplied separately as an optional feature","A component replacing another package during a planned upgrade"],0,"El grafo de dependencias incluye componentes directos y los que estos incorporan. También puede introducir vulnerabilidades en el producto."],
    ["¿Para qué sirve un SBOM?",["Para registrar componentes y versiones dentro de un producto","Para registrar vulnerabilidades y su prioridad de reparación por equipo","Para describir requisitos y criterios de aceptación seguros","Para acreditar la identidad del autor de cada componente"],0,"Un SBOM mejora la visibilidad y permite responder más rápido ante vulnerabilidades en componentes. Relaciona hallazgos con componentes y productos afectados."],
    ["What does an SCA tool do?",["Matching dependency versions against known vulnerability data","Inspecting application code for unsafe data flows and patterns","Exercising running endpoints with crafted external requests","Checking deployment settings against infrastructure policies"],0,"SCA ayuda a identificar versiones vulnerables, licencias y riesgos del software de terceros. Su detección depende del conocimiento disponible."],
    ["¿Qué es typosquatting?",["Publicar un paquete con un nombre casi igual al de uno legítimo","Publicar un paquete público con el nombre de uno interno","Introducir código malicioso en una nueva versión legítima del paquete","Distribuir una copia alterada desde un espejo no autorizado"],0,"Los nombres similares explotan errores tipográficos y hábitos de instalación. El engaño explota la similitud del nombre."],
    ["Which practice reduces the risk of a malicious package?",["Checking provenance and integrity of pinned package versions","Trusting a package because its name matches a familiar library","Trusting a package because it has many recent downloads","Accepting a package because its installation reports no errors"],0,"La procedencia, reproducibilidad y verificación de integridad son controles complementarios. La confianza exige verificar los componentes incorporados."],
    ["¿Por qué fijar versiones?",["Para controlar y reproducir las versiones de cada construcción","Para certificar que las versiones fijadas carecen de defectos","Para asegurar que la versión fijada recibe parches de seguridad automáticos","Para validar el origen de cada paquete mediante su número"],0,"Conviene combinar versiones fijadas con un proceso explícito de actualización. Controla el código de cada construcción."],
    ["What should a secure update process include?",["Risk review, compatibility tests and a verified rollback path","Installing the newest available build after checking its version number","Approving the update based on a successful download check","Replacing the build after reviewing its release announcement"],0,"La actualización debe ser trazable y poder revertirse si introduce regresiones. Actualizar puede introducir cambios incompatibles."],
    ["¿Qué verifica una firma digital de un componente?",["Integridad del artefacto y vinculación con un firmante confiable","Ausencia de código vulnerable según la identidad del firmante","Compatibilidad del artefacto con cualquier entorno de destino","Cumplimiento de requisitos seguros por usar una clave válida"],0,"Una firma no demuestra ausencia de vulnerabilidades; demuestra origen/integridad según la confianza configurada. Autenticidad e integridad no garantizan seguridad total."],
    ["What is a direct dependency?",["A dependency the project explicitly declares for its own use","A dependency introduced by another package in the project","A dependency discovered by scanning a deployed application","A dependency bundled by the build tool without an explicit declaration"],0,"Las dependencias transitivas llegan a través de otras dependencias. La declaración refleja una elección del proyecto."],
    ["¿Por qué revisar licencias además de vulnerabilidades?",["Porque imponen condiciones de uso y distribución del componente","Porque permiten estimar la gravedad de sus vulnerabilidades","Porque certifican la integridad de los archivos distribuidos","Porque determinan los permisos del componente al ejecutarse"],0,"La seguridad de la cadena de suministro incluye riesgos técnicos, operativos y legales. Distribuir componentes puede imponer obligaciones adicionales."]
  ],
  [
    ["Which validation checks whether a value is an integer?",["Expected type validation","Value range validation","Length limit validation","Encoding format validation"],0,"La validación de tipo confirma la clase de dato esperada; las demás cubren propiedades distintas. El tipo determina las operaciones válidas."],
    ["¿Por qué preferir una lista permitida?",["Porque limita la entrada a un conjunto definido como válido","Porque deduce la validez a partir de ataques ya observados","Porque acepta lo que no coincide con patrones sospechosos","Porque confía en lo que el navegador ya permitió enviar"],0,"Las listas permitidas suelen ser más robustas que intentar enumerar todas las entradas peligrosas. Los valores definidos evitan interpretaciones inesperadas."],
    ["What best prevents SQL injection?",["Prepared SQL queries that bind user values as parameters","String-built queries that remove selected SQL keywords","String-built queries that escape values with a custom filter","Dynamic queries whose error details are hidden from clients"],0,"El motor separa la estructura de la consulta de los datos suministrados. Los datos no se convierten en instrucciones."],
    ["¿Qué es path traversal?",["Manipular rutas para acceder fuera del directorio previsto","Sustituir contenido dentro de un archivo ya autorizado","Aprovechar permisos de escritura en un directorio compartido","Cambiar un enlace simbólico después de comprobar el archivo objetivo"],0,"Secuencias como ../ pueden escapar de la ubicación autorizada si no se valida la ruta. El destino supera el ámbito autorizado."],
    ["What is a defense against command injection?",["Calling a fixed executable with structured arguments, avoiding a shell","Quoting external input before concatenating it into a shell command","Blocking known shell separators before constructing a command string","Escaping spaces in external input before passing the command to a shell"],0,"Una API sin interpretación de shell reduce la posibilidad de que la entrada se convierta en sintaxis. Separa instrucciones ejecutables de datos externos."],
    ["¿Qué riesgo introduce deserializar datos no confiables?",["Activar objetos o comportamientos elegidos por un atacante","Enviar consultas parametrizadas con valores elegidos por el usuario","Rechazar tipos de objetos ajenos a una lista permitida","Leer valores simples con un parser de datos de alcance limitado"],0,"Debe usarse un formato seguro, tipos permitidos y límites adecuados. Reconstruir objetos puede activar lógica inesperada."],
    ["What does normalizing input mean?",["Converting equivalent representations to a canonical form","Removing characters that match a known malicious pattern","Encoding characters for a specific output rendering context","Verifying that values satisfy the permitted business rules"],0,"La canonicalización evita que una validación y el uso posterior interpreten el dato de forma distinta. Interpretaciones diferentes permiten evadir comprobaciones."],
    ["¿Qué problema puede causar una expresión regular vulnerable?",["Retrocesos excesivos que agotan la CPU y pueden provocar ReDoS","Un fallo de integridad que cambia el certificado TLS del servicio","Una confusión de tipos que ejecuta objetos durante el parseo","Una escritura fuera del buffer por superar el rango de un entero"],0,"Las expresiones ambiguas sobre entradas largas pueden bloquear recursos. Su coste puede crecer desproporcionadamente."],
    ["Why validate on the server if input was already validated on the client?",["Client checks can be bypassed when submitting external input","Client checks cover syntax while servers only verify text encoding","Encrypted transport guarantees data came from validated fields","A valid session establishes trust in every submitted field"],0,"La validación del cliente mejora UX; la del servidor protege el recurso. El cliente permite omitir sus propias comprobaciones."],
    ["¿Qué debe limitar un parser JSON expuesto a usuarios?",["Tamaño, profundidad, tipos y coste de procesamiento","Orden de las claves, sangría y estilo de representación","Navegador, resolución y tamaño de la ventana usada","Número de endpoints, métodos HTTP y nombres de rutas"],0,"Los límites reducen abuso de recursos y estructuras inesperadas. La sintaxis válida no controla los recursos."]
  ],
  [
    ["What is a buffer overflow?",["Writing beyond the allocated bounds of a memory buffer","Reading a freed allocation through a stale memory pointer","Losing the last reference to an unreleased memory allocation","Wrapping an integer calculation beyond its representable range"],0,"Puede corromper memoria, provocar un fallo o permitir ejecución de código. La escritura alcanza memoria fuera del destino."],
    ["¿Qué puede causar un integer overflow?",["Una operación que supera el rango representable del entero","Una conversión decimal que pierde precisión de fracciones","Una comparación que mezcla magnitudes con unidades distintas","Una lectura binaria que usa un orden de bytes equivocado"],0,"Las comprobaciones de rango y tipos adecuados evitan resultados inesperados. El resultado puede no representar el cálculo."],
    ["What does authentication mean?",["Verifying the claimed identity of a user or service","Checking whether a user may perform a specific operation","Checking that a received record has not been altered","Recording evidence to attribute an approved transaction"],0,"Autenticación responde “¿quién eres?”; autorización responde “¿qué puedes hacer?”. Autenticar no concede permisos sobre todo."],
    ["¿Qué debe comprobar una autorización?",["La identidad, la acción, el recurso y el contexto de acceso","La identidad, el certificado TLS y el algoritmo de cifrado","El token, su formato y la fecha en que se emitió la sesión","El origen, la dirección IP y el agente de usuario del cliente"],0,"La decisión debe basarse en una política explícita y en el contexto correcto. El acceso depende de la política aplicable."],
    ["Which cookie attribute prevents access from JavaScript?",["HttpOnly, which prevents scripts from reading the cookie","Secure, which restricts scripts to pages served over HTTPS","SameSite, which hides cookies from scripts running in other tabs","Path, which limits cookie reads to scripts in that folder"],0,"HttpOnly reduce el robo de cookies mediante scripts; no elimina todos los riesgos de XSS. Restringe el acceso directo desde scripts."],
    ["¿Qué indica Secure en una cookie?",["Que la cookie se transmite por conexiones HTTPS","Que la cookie se almacena cifrada en el navegador","Que la cookie no puede leerse desde JavaScript","Que la cookie autentica por sí misma al servidor"],0,"Secure protege el transporte de la cookie frente a canales no cifrados. Impide enviar esa cookie por transporte desprotegido."],
    ["What helps mitigate CSRF?",["An anti-CSRF token with a suitable SameSite cookie policy","An HttpOnly cookie with a strict HTML output encoding rule","An encrypted session cookie with a longer fixed expiration period","A restrictive CORS policy with an origin check in client code"],0,"CSRF abusa de credenciales del navegador para forzar acciones no deseadas. Una sesión no demuestra intención del usuario."],
    ["¿Qué controla CORS?",["Qué orígenes pueden leer respuestas entre orígenes en el navegador","Qué usuarios pueden consultar cada recurso protegido del servidor","Qué solicitudes pueden llegar desde clientes externos a la API","Qué cookies pueden enviarse al cambiar de sitio en el navegador"],0,"CORS es una política del navegador; no sustituye la autorización del servidor. El navegador controla lecturas entre orígenes."],
    ["What is a memory leak?",["Allocated memory that is no longer needed but remains unreleased","Allocated memory accessed after its allocation has been freed","Allocated memory overwritten beyond the bounds of its buffer","Allocated memory mapped with write access for another process"],0,"Las fugas degradan el servicio y pueden acabar en denegación de servicio. La pérdida reduce los recursos disponibles."],
    ["¿Qué aporta SameSite?",["Limita el envío de cookies en ciertos contextos entre sitios","Limita el acceso a cookies desde scripts del mismo dominio","Limita el envío de cookies a conexiones protegidas mediante TLS","Limita el uso de cookies a una carpeta concreta dentro del servidor"],0,"SameSite limita el envío contextual de cookies y puede ayudar contra CSRF. El contexto determina cuándo se envía."]
  ],
  [
    ["Why avoid system() with user input?",["The shell can treat supplied metacharacters as command syntax","The shell can expose its executable path in ordinary error output","The shell can inherit a working directory different from the caller","The shell can load environment settings before running the command"],0,"Separar comando y argumentos mediante una API segura es la opción preferible. El intérprete convierte metacaracteres en instrucciones."],
    ["¿Qué es pipe-to-shell?",["Descargar contenido y enviarlo a un intérprete para ejecutarlo","Descargar un paquete y verificarlo antes de invocar su instalador","Leer un archivo de configuración como datos dentro del proceso principal","Canalizar la salida de un proceso a un archivo sin interpretarla"],0,"El contenido remoto se ejecuta antes de poder inspeccionarlo y verificarlo. Impide evaluar previamente el contenido ejecutado."],
    ["What does a secure path check validate?",["Its resolved target remains inside the authorized directory","Its file extension matches one of the supported document formats","Its textual prefix matches the authorized directory name","Its final filename contains none of the blocked characters"],0,"Resolver y comprobar el prefijo/base autorizada evita escapes de directorio. La ruta textual no garantiza autorización."],
    ["¿Qué principio aplica a archivos temporales?",["Creación atómica, permisos restrictivos y limpieza controlada","Creación en carpeta compartida y borrado al cerrar la aplicación","Creación con nombre fijo y comprobación previa de que no exista","Creación con permisos heredados y cambio de permisos al terminar"],0,"Los temporales son recursos compartidos y deben protegerse frente a lectura, enlaces y agotamiento. Compartir recursos exige evitar accesos inesperados."],
    ["What does HTTPS/TLS provide?",["Channel confidentiality and integrity, plus server authentication","Stored-data confidentiality and integrity, plus user authorization","Request validation and session integrity, plus client authorization","Application-code integrity and origin, plus endpoint vulnerability checks"],0,"TLS protege el transporte, pero no corrige controles de aplicación deficientes. Sus garantías corresponden al canal de comunicación."],
    ["¿Qué debe verificarse al instalar un binario?",["Procedencia e integridad, con firmas y una fuente de confianza","Popularidad del proveedor, fecha del archivo y tamaño del binario","Disponibilidad del enlace, extensión del archivo y texto del nombre","Compatibilidad del sistema, tiempo de descarga y código de salida"],0,"La cadena de instalación debe ser verificable y reproducible. La apariencia no demuestra procedencia confiable."],
    ["Why limit the permissions of a process that runs commands?",["To contain damage if the command-running process is compromised","To prevent user input from containing shell command metacharacters","To ensure every permitted command is free of exploitable defects","To establish the integrity of binaries invoked by the process"],0,"El mínimo privilegio limita las acciones posteriores a una explotación. Las capacidades delimitan el impacto posible."],
    ["¿Qué riesgo tiene aceptar nombres de archivo arbitrarios?",["Sobrescribir archivos, escapar de rutas o provocar colisiones","Aceptar varios idiomas al presentar el nombre en la interfaz","Rechazar una extensión que no pertenece al formato esperado","Reducir la longitud del nombre antes de guardarlo en la base de datos"],0,"El nombre debe validarse como dato y no convertirse en una ruta controlada por el atacante. El nombre afecta selección y sobrescritura."],
    ["What is a command allowlist?",["A defined set of approved operations and their permitted arguments","A list of command fragments rejected because they look dangerous","A list of executable files found by searching the current PATH","A set of previously successful commands recovered from audit logs"],0,"Limitar las operaciones es más seguro que intentar bloquear todas las variantes peligrosas. Reduce las instrucciones accesibles desde el exterior."],
    ["¿Qué debe hacer un instalador seguro ante una firma inválida?",["Bloquear la instalación y comprobar la procedencia del artefacto","Reintentar la instalación desactivando la comprobación de confianza","Aceptar el artefacto si su hash coincide con uno incluido en él","Instalar el artefacto si su número de versión es posterior al registrado"],0,"Una verificación fallida debe ser un fallo cerrado y visible. Continuar aceptaría contenido sin confianza demostrada."]
  ],
  [
    ["Which defense adapts HTML output to its context?",["Encoding data for its specific HTML, attribute or script context","Encoding every value with HTML entities regardless of where it goes","Filtering submitted values for a fixed list of suspicious tag names","Applying URL encoding to every value before placing it in the page"],0,"La codificación debe corresponder al contexto donde se inserta el dato. Cada contexto interpreta caracteres de forma distinta."],
    ["¿Qué es XSS almacenado?",["Una carga maliciosa guardada que se ejecuta al mostrarla a usuarios","Una carga maliciosa reflejada desde la solicitud en su respuesta","Una carga maliciosa interpretada por el DOM sin quedar almacenada","Una carga maliciosa ejecutada por el servidor al formar una consulta"],0,"El contenido persistido se ejecuta en el navegador de las víctimas al renderizarse. Persistir permite afectar a víctimas posteriores."],
    ["What should a public error message avoid?",["Stack traces, internal paths, secrets and query details","A generic failure description and a public incident reference","A controlled retry instruction and the expected input format","A stable error code and a link to the public support channel"],0,"Los detalles útiles para diagnóstico deben ir a canales protegidos y controlados. Los detalles internos pueden facilitar ataques."],
    ["¿Qué característica hace útil un log de seguridad?",["Actor, evento, momento, resultado y contexto para investigarlo","Payload completo, credenciales, cookies y cabeceras del cliente","Código fuente, configuración, secretos y rutas de cada servicio","Uso de CPU, memoria, latencia y volumen agregado de solicitudes"],0,"La trazabilidad requiere datos consistentes sin registrar secretos innecesarios. El contexto permite reconstruir los eventos."],
    ["What is log injection?",["Crafting input that forges or alters the interpretation of log entries","Generating many legitimate events to increase log storage consumption","Reading restricted log files through a missing access control rule","Deleting stored log files after obtaining server administrator access"],0,"La codificación y normalización de campos evita que la entrada simule eventos. La entrada puede modificar la interpretación."],
    ["¿Qué dato no debe registrarse normalmente?",["Contraseñas, tokens de sesión y claves privadas en texto legible","Marcas de tiempo y códigos del resultado de una autenticación","Identificadores de correlación y duración de cada solicitud","Tipo de evento y referencia interna del componente afectado"],0,"Los secretos deben excluirse o enmascararse; los logs también son información sensible. El registro puede exponer credenciales utilizables."],
    ["Which privacy principle applies to logging?",["Collect only data needed for a defined logging purpose","Collect available data first and decide its purpose afterward","Collect full request bodies and restrict access to the log viewer","Collect user profiles once and reuse them for unrelated analysis"],0,"La minimización reduce exposición y obligaciones de protección de datos. Minimizar reduce exposición y usos innecesarios."],
    ["¿Qué diferencia una excepción de un código de retorno?",["La excepción desvía el flujo a un manejador; el retorno entrega un resultado","La excepción entrega un valor al llamador; el retorno activa un manejador","La excepción permite ignorar un fallo; el retorno obliga a gestionarlo","La excepción libera todos los recursos; el retorno conserva los abiertos"],0,"Ambos deben manejarse de forma explícita, sin ocultar fallos ni filtrar información. Ambos requieren manejar explícitamente sus resultados."],
    ["What is the safest response to an authorization failure?",["Deny access and return a controlled failure response","Keep the request pending while using cached permissions","Retry the request under a more privileged service account","Complete the read operation while recording an audit warning"],0,"La política debe fallar de forma segura y dejar evidencia útil, sin filtrar detalles. La incertidumbre no debe conceder acceso."],
    ["¿Qué ayuda contra XSS además de escapar salidas?",["CSP y sanitización contextual; HttpOnly limita el robo de cookies","CORS y cifrado de cookies; ambos bloquean scripts inyectados","SameSite y cookies Secure; ambos impiden insertar scripts en el contenido HTML","Tokens anti-CSRF y TLS; ambos validan el contenido mostrado"],0,"Ninguna capa sustituye la codificación correcta, pero varias reducen impacto y probabilidad. Las defensas cubren vías e impactos distintos."]
  ],
  [
    ["What does SAST primarily find?",["Risk patterns in source code or bytecode without running the app","Risky responses observed while sending crafted requests to a running app","Known vulnerable versions in a software dependency inventory","Memory access violations observed during instrumented execution"],0,"SAST analiza artefactos estáticos y puede integrarse temprano en CI. Analiza patrones sin ejecutar el sistema."],
    ["¿Qué caracteriza a DAST?",["Evalúa una aplicación en ejecución mediante entradas observables","Evalúa el código fuente mediante reglas y análisis de flujo de datos","Evalúa versiones de dependencias frente a avisos de seguridad conocidos","Evalúa el diseño mediante diagramas de flujo y fronteras de confianza"],0,"DAST detecta problemas que aparecen en el comportamiento desplegado. Observa el comportamiento de una aplicación ejecutándose."],
    ["What are regression tests for?",["Detecting whether changes reintroduce previously fixed defects","Finding unknown defects by continuously mutating generated inputs","Measuring which statements and branches a test suite executes","Estimating exploit likelihood from the latest vulnerability reports"],0,"Una regresión ocurre cuando una modificación rompe una propiedad previamente satisfecha. Protege correcciones frente a modificaciones posteriores."],
    ["¿Qué es fuzzing?",["Generar o mutar entradas para revelar fallos y conservar casos útiles","Recorrer funciones del código aplicando reglas sin ejecutar el sistema","Repetir los casos de negocio aprobados con las mismas entradas fijas","Comparar versiones instaladas con un catálogo de defectos conocidos"],0,"Fuzzing explora casos que quizá no fueron previstos por las pruebas tradicionales. Explora combinaciones no anticipadas manualmente."],
    ["What does coverage measure?",["The code or conditions exercised by the executed tests","The exploitable defects eliminated by the executed tests","The input combinations that cannot cause future failures","The business risks accepted after the security review"],0,"Alta cobertura no garantiza seguridad, pero ayuda a detectar zonas sin ejercitar. Mide ejecución, no calidad de las comprobaciones."],
    ["¿Qué aporta ASAN?",["Detecta accesos inválidos a memoria al ejecutar código instrumentado","Detecta dependencias de terceros vulnerables sin ejecutar el código del producto","Detecta errores de autorización al observar peticiones entre usuarios","Detecta patrones inseguros al recorrer estáticamente el código fuente"],0,"Sanitizadores como AddressSanitizer ayudan a encontrar accesos fuera de límites y use-after-free. Detecta accesos inválidos durante ejecuciones instrumentadas."],
    ["What does an effective manual review do?",["Assessing business logic, trust assumptions and control boundaries","Approving the design when automated scanners report no findings","Reviewing code formatting and naming without tracing security flows","Checking public interfaces without examining ownership or access rules"],0,"La revisión humana encuentra problemas de diseño y lógica que una herramienta puede no comprender. El contexto revela decisiones lógicamente inseguras."],
    ["¿Qué es una semilla en fuzzing?",["Una entrada inicial usada para explorar el formato y generar mutaciones","Un valor secreto usado para cifrar las entradas que genera la herramienta","Un informe final usado para ordenar las vulnerabilidades por gravedad","Un umbral de cobertura usado para detener la ejecución de las pruebas"],0,"Buenas semillas ayudan a llegar a estados y rutas más profundas. Permite comenzar exploraciones con entradas representativas."],
    ["What should a reproducible finding contain?",["Exact steps, input, environment, impact and supporting evidence","A risk score, scanner brand, report date and remediation deadline","An error screenshot, issue title, assignee and estimated fix cost","A recommended patch, affected team, review status and release plan"],0,"La reproducibilidad acelera la corrección y reduce falsos positivos. La evidencia permite comprobar y corregir defectos."],
    ["¿Qué práctica es apropiada en bug bounty?",["Respetar el alcance acordado y coordinar la comunicación del hallazgo","Ampliar pruebas a servicios vinculados que no figuran en el alcance","Publicar pruebas de explotación antes de usar el canal del programa","Validar el impacto con datos de usuarios ajenos sin permiso expreso"],0,"La investigación debe ser autorizada y seguir reglas claras para reducir daño. La autorización delimita la investigación permitida."]
  ],
  [
    ["What does a process represent in a DFD?",["A transformation that receives, processes or produces data","An external actor that exchanges information with the system","A store that retains information for retrieval by the system","A connection that carries information between system elements"],0,"Los DFD modelan movimiento y transformación de información, no solo infraestructura. Representa operaciones sobre datos en movimiento."],
    ["¿Qué es una frontera de confianza?",["Un límite donde cambian los supuestos de confianza sobre los datos","Un límite donde cambia el formato elegido para representar los datos","Un límite donde cambia la velocidad de transmisión de los datos","Un límite donde cambia el lenguaje del componente que usa los datos"],0,"Cada cruce requiere considerar autenticación, validación y controles apropiados. La confianza no se transfiere automáticamente."],
    ["What does the S in STRIDE stand for?",["Spoofing: impersonating an entity","Sniffing: intercepting network traffic","Scanning: discovering exposed services","Spamming: flooding unsolicited messages"],0,"STRIDE agrupa amenazas: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service y Elevation of Privilege. La identidad presentada no corresponde al actor."],
    ["¿Qué amenaza STRIDE representa modificar datos?",["Tampering: alterar datos sin autorización","Spoofing: asumir la identidad de otra entidad","Repudiation: negar la autoría de una operación","Disclosure: revelar información a terceros"],0,"Tampering es una alteración no autorizada de datos o código. La modificación compromete contenido o comportamiento esperado."],
    ["Which threat corresponds to denying an action that was performed?",["Repudiation: denying responsibility for an action","Spoofing: claiming a different identity during an action","Tampering: modifying records that describe an action","Disclosure: exposing protected details about an action"],0,"Controles como auditoría confiable y firmas ayudan a abordar el repudio. Sin evidencia resulta difícil atribuir acciones."],
    ["¿Qué es elevación de privilegios?",["Adquirir capacidades por encima de las autorizadas para la identidad","Autenticarse con otra identidad que ya dispone de los mismos permisos","Ocultar una acción autorizada borrando sus evidencias de auditoría","Interrumpir funciones autorizadas agotando recursos del servicio"],0,"Puede ser horizontal o vertical según el nivel de privilegio obtenido. Otorga capacidades fuera del ámbito autorizado."],
    ["What does a good threat model prioritize?",["Threat scenarios ranked by likelihood, impact and feasible controls","Scan findings ranked mainly by the total number of matching alerts","Diagram components ranked mainly by the complexity of their design","Mitigations ranked mainly by their purchase and operating costs"],0,"La priorización convierte el modelado en decisiones accionables. El esfuerzo debe corresponder al riesgo."],
    ["¿Qué ventaja aporta un DFD?",["Permite analizar amenazas al ver flujos, almacenes y límites de confianza","Permite certificar controles al dibujar cada componente de la solución","Permite detectar vulnerabilidades al medir el tamaño de los flujos","Permite demostrar seguridad al completar las figuras del diagrama"],0,"Un diagrama simple ayuda a descubrir puntos de entrada y datos sensibles. Expone puntos que necesitan análisis de confianza."],
    ["Which threat affects availability?",["Denial of Service through resource exhaustion","Information Disclosure through unauthorized reads","Tampering through unauthorized changes to records","Spoofing through misuse of an existing identity"],0,"DoS busca degradar o impedir que un servicio esté disponible. Impedir acceso oportuno afecta la disponibilidad."],
    ["¿Qué debe producir un threat model útil?",["Escenarios priorizados, supuestos y mitigaciones que puedan comprobarse","Un diagrama detallado, nombres de servicios y un catálogo de tecnologías","Una lista de herramientas, sus licencias y estimaciones de instalación","Un inventario de archivos, sus tamaños y métricas de estilo del código"],0,"El resultado debe conectar riesgos con controles y responsables. Relaciona riesgos, mitigaciones y pruebas de cumplimiento."]
  ],
  [
    ["What property does a secure cryptographic hash have?",["Finding distinct inputs with the same digest is computationally hard","The digest changes randomly each time the same input is processed","The digest hides the input using a shared encryption secret","The original input can be recovered if its digest is known"],0,"Las funciones hash no son cifrado; buscan resistencia a preimagen y colisiones según el uso. La resistencia depende de la propiedad evaluada."],
    ["¿Por qué no usar MD5 para seguridad?",["Porque permite construir entradas distintas con el mismo resumen","Porque exige una clave secreta distinta para resumir cada archivo","Porque su resumen cambia al repetirlo sobre una misma entrada","Porque el resumen permite reconstruir directamente cualquier archivo"],0,"MD5 no es adecuado para integridad adversarial o firmas modernas. Las colisiones comprometen la distinción entre contenidos."],
    ["What is the difference between symmetric and asymmetric encryption?",["Symmetric encryption uses a shared key; asymmetric uses a key pair","Symmetric encryption uses a key pair; asymmetric relies on a shared secret key","Symmetric encryption protects stored data; asymmetric protects network data","Symmetric encryption authenticates data; asymmetric only conceals data"],0,"Cada modelo resuelve necesidades distintas de confidencialidad, intercambio y firma. Las relaciones entre claves permiten operaciones distintas."],
    ["¿Qué es AES?",["Un cifrador simétrico que opera sobre bloques de datos","Un generador criptográfico que produce secuencias de bits","Un esquema asimétrico que permite intercambiar claves","Un algoritmo de resumen que produce huellas de longitud fija"],0,"AES se usa ampliamente para cifrado simétrico cuando se emplea con un modo seguro. Procesa bloques dentro de un esquema criptográfico."],
    ["What does a 256-bit key mean?",["Its ideal keyspace contains 2^256 possible bit patterns","Every attack must perform exactly 2^256 computational steps","Every message is processed in blocks of exactly 256 bits","Each stored secret occupies exactly 256 bytes of key data"],0,"Bits de clave no equivalen a bytes ni garantizan por sí solos una implementación correcta. Expresa posibilidades, no seguridad de implementación."],
    ["¿Qué aporta una firma digital?",["Integridad del contenido y autenticidad con una clave pública confiable","Confidencialidad del contenido al verificarlo con la clave pública","Disponibilidad del contenido mediante su validación criptográfica","Ausencia de vulnerabilidades en el contenido que firma el proveedor"],0,"La firma se verifica con una clave pública y no sustituye el cifrado si se necesita secreto. Vincula contenido con una clave de firma."],
    ["What is a CSPRNG?",["A random generator designed to resist prediction by an adversary","A deterministic generator designed to distribute samples uniformly","A generator designed to reproduce simulation results from a fixed seed","A timestamp-based generator designed to avoid duplicate values"],0,"Debe producir valores impredecibles frente a un atacante con información parcial. La impredecibilidad protege futuros valores secretos."],
    ["¿Por qué importa la gestión de claves?",["Porque la exposición de claves puede anular la protección criptográfica","Porque aumentar la longitud de la clave sustituye su revocación","Porque fijar una clave evita comprobar la identidad de quien la usa","Porque un algoritmo robusto recupera por sí mismo las claves filtradas"],0,"Protección, ciclo de vida, rotación y acceso a claves son parte del diseño criptográfico. La protección depende de claves confiables."],
    ["What is responsible disclosure?",["Coordinating a report with those responsible and allowing time to fix it","Publishing exploit details as soon as the vulnerability is confirmed","Reporting the flaw publicly before contacting the affected maintainers","Sharing live access credentials so others can verify the vulnerable system"],0,"Busca equilibrar transparencia, seguridad de usuarios y capacidad de respuesta del proveedor. La coordinación reduce exposición mientras se corrige."],
    ["¿Qué es un despliegue seguro?",["Publicar artefactos verificados con configuración segura y reversión","Publicar un artefacto compilado sin revisar su configuración de destino","Publicar la versión reciente si las pruebas funcionales terminaron bien","Publicar tras una revisión de código sin comprobar el artefacto generado"],0,"La seguridad debe continuar en la entrega y operación, no terminar al compilar. La operación puede debilitar garantías del desarrollo."]
  ]
];
// Los enunciados y opciones de cinco preguntas por módulo se presentan en inglés.
let questions=[]; topics.forEach((group,d)=>group.forEach((q,i)=>questions.push({day:d,text:q[0],options:q[1],answer:q[2],explain:q[3],language:i%2===0?'en':'es',difficulty:i%3===0?'INTERMEDIO':i%3===1?'AVANZADO':'EXPERTO'})));
// Un ejemplo y una idea clave específicos para cada una de las 100 preguntas.
const feedbackNotes=[
  [
    ['En una tienda en línea, la base de clientes, las credenciales y el servicio de pagos son activos que necesitan protección. Si se exponen, pueden causar fraude y pérdida de confianza.','Un activo es lo que proteges; una amenaza puede dañarlo y una vulnerabilidad facilita ese daño. Identifica qué perderías si ese activo resulta comprometido.'],
    ['Una interrupción de pagos puede ser poco frecuente, pero su impacto comercial puede justificar controles y respaldos. Después compara ese impacto con el coste de las medidas.','No confundas riesgo con vulnerabilidad: el riesgo incorpora la probabilidad y las consecuencias en un contexto concreto. La debilidad aislada no describe el riesgo completo.'],
    ['Solo el personal autorizado debería poder consultar los expedientes de los clientes, incluso si conoce su ubicación. Una cuenta de otro departamento debería recibir una denegación.','Cifrar ayuda a proteger la confidencialidad, pero también necesitas controlar quién puede acceder y qué puede leer. Revisa copias, exportaciones y permisos sobre los respaldos.'],
    ['Cambiar el importe de una factura sin autorización compromete su integridad aunque el sistema siga disponible. Compara el importe original con el historial de modificaciones.','Integridad significa evitar o detectar modificaciones indebidas; disponibilidad significa poder acceder cuando se necesita. Identifica quién modificó el dato y cuándo.'],
    ['Un servicio de reservas necesita seguir respondiendo ante fallos de un servidor o aumentos de tráfico. Una réplica puede atender solicitudes mientras se recupera el servidor.','Respaldos, redundancia y recuperación ayudan a la disponibilidad; deben probarse para comprobar que realmente funcionan. Define interrupciones y pérdidas tolerables para el servicio.'],
    ['Una aprobación firmada y registrada con una identidad verificada aporta evidencia sobre quién autorizó una operación. Conserva el contenido aprobado y la fecha junto a la firma.','La calidad de la evidencia depende de proteger las claves, verificar identidades y evitar modificaciones de los registros. Compartir cuentas dificulta atribuir una acción individual.'],
    ['Al inventariar una base de pagos, registra su responsable, los servicios que la usan y el impacto de perderla. Incluye cómo se restauraría y cuánto tardaría esa recuperación.','Un inventario útil relaciona cada activo con su dueño y su impacto, no solo con una dirección o un nombre. Las dependencias pueden amplificar un fallo inicialmente pequeño.'],
    ['Un atacante que intenta robar datos es una amenaza; una consulta SQL construida sin parámetros puede ser una vulnerabilidad. Parametrizar la consulta reduce esa vía concreta de explotación.','La amenaza describe el posible daño o su agente; la vulnerabilidad describe la debilidad que puede aprovechar. Un control trata debilidades o reduce sus consecuencias.'],
    ['Verificar la firma de una actualización ayuda a comprobar su procedencia, según la confianza en la clave del firmante. Una firma de un desconocido no acredita al publicador esperado.','Un dato íntegro no necesariamente procede de quien crees: autenticidad e integridad son propiedades relacionadas, pero distintas. Verifica al firmante, no únicamente su firma.'],
    ['Un catálogo público y una tabla de contraseñas no deberían recibir las mismas reglas de acceso y retención. La tabla sensible requiere acceso restringido incluso para personal interno.','Clasificar permite asignar controles proporcionales a la sensibilidad, el valor y las consecuencias de exposición. Reclasifica cuando cambie el contenido o su uso.']
  ],
  [
    ['Un requisito concreto puede exigir que los usuarios solo consulten sus propios pedidos y que esto se pruebe automáticamente. Prueba también que cambiar el identificador no permita consultar pedidos ajenos.','Transforma objetivos como “proteger los datos” en condiciones observables que permitan aprobar o rechazar una prueba. Incluye rechazos, no únicamente los accesos permitidos.'],
    ['Durante el diseño de un sistema de pagos ya se deben identificar los datos sensibles y sus fronteras de confianza. Esto permite decidir antes dónde cifrar y restringir el acceso.','La seguridad atraviesa requisitos, diseño, implementación, pruebas, entrega y operación; no es una revisión final aislada. Corregir diseños temprano evita cambios posteriores costosos.'],
    ['El proceso que genera reportes puede tener acceso de lectura sin permiso para eliminar tablas de la base de datos. Si esa cuenta es robada, no debería permitir borrar registros.','Asigna permisos por función y revisa también cuentas técnicas, servicios y tareas automáticas. Reduce permisos cuando una función deje de necesitarlos.'],
    ['Una API puede combinar autorización, validación de entradas, consultas parametrizadas y monitoreo de actividad. Si falla la validación, la parametrización todavía separa datos y SQL.','Cada capa debe aportar un control real: varias barreras reducen la dependencia de una sola defensa. Comprueba que las capas no compartan el mismo fallo.'],
    ['Un panel administrativo puede quedar deshabilitado o restringido hasta que su acceso se configure explícitamente. Así una instalación nueva no expone públicamente funciones sensibles.','El usuario que conserva la configuración inicial debe recibir una protección razonable sin activar opciones adicionales. Habilita excepciones de forma explícita y controlada.'],
    ['Aunque un usuario haya iniciado sesión, cada descarga de un documento debe comprobar su permiso sobre ese documento. Si revocas el acceso, la siguiente descarga debe ser rechazada.','Una autenticación previa no autoriza automáticamente todos los recursos ni todas las acciones posteriores. Comprueba cada recurso aunque la sesión siga válida.'],
    ['Un protocolo puede ser público mientras mantiene protegidas las claves que permiten autenticar y cifrar sus mensajes. Un análisis del protocolo puede descubrir defectos sin revelar las claves.','Ocultar detalles internos no sustituye un mecanismo que resista análisis; las claves sí requieren protección. Distingue diseño público de secretos que requieren protección.'],
    ['Eliminar un endpoint de depuración que no se usa evita exponer una función innecesaria en producción. La eliminación también evita mantener sus permisos y dependencias asociadas.','Revisa funciones, puertos, privilegios y dependencias: cada elemento expuesto añade algo que proteger. Menos componentes facilitan revisión, actualización y monitoreo.'],
    ['Una prueba puede verificar que una cuenta sin permiso recibe una denegación al intentar eliminar un pedido. Comprueba además que el pedido siga existiendo después del rechazo.','Define el contexto, la acción y el resultado esperado; así el requisito puede convertirse en una prueba reproducible. Verifica el resultado, no solo el mensaje mostrado.'],
    ['Separar el servicio de pagos del sitio público cambia los accesos posibles y las consecuencias de comprometer un componente. Un compromiso del sitio no debería dar acceso directo a pagos.','Evalúa cómo cada decisión modifica flujos, confianza, privilegios y alcance de una posible explotación. Documenta los supuestos de cada frontera de confianza.']
  ],
  [
    ['Si tu aplicación utiliza A y A necesita B, B forma parte del producto aunque no la hayas declarado directamente. Actualizar A puede cambiar B sin modificar tu código directamente.','Revisar solo las dependencias directas deja fuera parte del código incorporado al producto. Inspecciona el árbol y sus versiones realmente incorporadas.'],
    ['Ante una vulnerabilidad en una biblioteca, el SBOM permite localizar qué productos incluyen la versión afectada. El equipo puede priorizar actualizaciones y avisar a responsables concretos.','El inventario debe reflejar lo que realmente se entrega y actualizarse cuando cambian los componentes. Un inventario desactualizado puede ocultar componentes de producción.'],
    ['Una revisión SCA puede detectar que una biblioteca instalada coincide con una versión vulnerable conocida. Luego determina si esa dependencia se utiliza en funciones expuestas.','Un análisis de dependencias complementa las pruebas de la aplicación; no demuestra ausencia de problemas de lógica. Investiga aplicabilidad e impacto antes de cerrar alertas.'],
    ['Un nombre como “reqeusts” puede intentar parecerse al paquete legítimo “requests” para provocar una instalación equivocada. Revisar el publicador ayuda a distinguir ambos antes de instalar.','Comprueba el nombre, el publicador y la procedencia antes de incorporar un paquete. Un nombre parecido no prueba legitimidad del paquete.'],
    ['Un proceso de instalación puede usar un registro aprobado y verificar que el artefacto coincide con el esperado. Rechaza la instalación si el artefacto recibido no coincide.','Un hash solo ayuda si el valor esperado llega por un canal confiable; procedencia e integridad se complementan. Controla quién puede publicar y modificar componentes aprobados.'],
    ['Una versión fijada evita que dos construcciones descarguen silenciosamente versiones diferentes de la misma biblioteca. Así puedes reproducir un fallo con el mismo conjunto de componentes.','Reproducibilidad no significa congelar dependencias para siempre: incluye un proceso de actualización y pruebas. Conserva información para reconstruir exactamente lo entregado.'],
    ['Antes de actualizar una biblioteca, revisa sus cambios, ejecuta las pruebas y prepara cómo volver a la versión anterior. Valida flujos críticos en un entorno de prueba antes de desplegar.','Actualizar con seguridad combina evaluación, validación y una recuperación definida si algo falla. Planifica actualización y recuperación ante posibles fallos.'],
    ['Un archivo firmado puede verificarse contra una clave de confianza para detectar alteraciones desde su firma. El código firmado aún puede requerir análisis y pruebas adicionales.','Una firma válida no certifica que el código esté libre de vulnerabilidades o comportamientos peligrosos. Verifica la clave confiable y el contenido firmado.'],
    ['Una biblioteca declarada explícitamente en el manifiesto de la aplicación es una dependencia directa. Si esa biblioteca incorpora otra, la segunda será transitiva.','Distingue lo declarado por tu proyecto de lo que incorporan esos componentes; ambos niveles necesitan seguimiento. La categoría no elimina la necesidad de revisión.'],
    ['La distribución de un producto puede estar condicionada por las licencias de las bibliotecas que incluye. Por ejemplo, puede exigir conservar avisos de autoría o licencia.','Una dependencia técnicamente adecuada también debe poder usarse y distribuirse conforme a sus obligaciones. Registra obligaciones, versiones y procedencia del componente.']
  ],
  [
    ['Si un campo representa una cantidad entera, aceptar texto arbitrario o un número con decimales incumple el tipo esperado. Una cantidad negativa necesitaría además una comprobación independiente de rango.','Tipo, rango, longitud y formato son comprobaciones diferentes; una sola no sustituye a las demás. El tipo válido no garantiza un valor aceptable.'],
    ['Un parámetro de ordenación puede aceptar únicamente “fecha” o “precio” en lugar de recibir una expresión libre. Cualquier otra cadena debería rechazarse, no convertirse en una expresión.','Define lo válido y rechaza lo restante; también establece límites de tamaño y una interpretación consistente. Mantén explícita y pequeña la lista autorizada.'],
    ['En una consulta parametrizada, el nombre ingresado se envía como dato y no como una parte de la sintaxis SQL. Incluso una comilla maliciosa permanece dentro del valor del parámetro.','Los parámetros son para valores; los identificadores dinámicos, como nombres de columnas, requieren un tratamiento controlado. Mantén separados datos e instrucciones en cada consulta.'],
    ['Una descarga que acepta “../../configuracion” puede intentar acceder a un archivo fuera del directorio autorizado. La aplicación debe negar ese destino aunque el archivo exista.','Resolver una ruta no basta: comprueba que el resultado permanezca dentro de la ubicación permitida. Comprueba directorios, permisos y enlaces cuando corresponda.'],
    ['En vez de concatenar un nombre en una orden de shell, utiliza una API que reciba el programa y sus argumentos separados. Un nombre con metacaracteres no debería crear una segunda orden.','Evitar el shell reduce interpretación de metacaracteres; valida también qué argumentos permite el programa invocado. Limita las opciones del programa que será invocado.'],
    ['Un formato que permite reconstruir objetos con comportamientos puede ejecutar acciones no previstas al recibir datos externos. Una lista de tipos permitidos restringe qué estructuras pueden reconstruirse.','Prefiere estructuras de datos simples y tipos explícitos, con límites de profundidad, tamaño y procesamiento. La sintaxis válida no garantiza objetos ejecutables seguros.'],
    ['Dos representaciones de una ruta pueden apuntar al mismo destino aunque sus cadenas de texto sean diferentes. Comprueba el destino después de resolver su representación canónica.','Valida la representación que realmente se utilizará; evita validar una forma y ejecutar otra. Valida conforme al uso final del dato.'],
    ['Un patrón con repeticiones ambiguas puede tardar mucho en rechazar una cadena especialmente construida. Mide también el tiempo de rechazo, no solo el de aceptación.','Limita las entradas y revisa el comportamiento del patrón ante casos largos y fallidos, no solo casos válidos. Evita patrones ambiguos y limita la entrada.'],
    ['Un atacante puede enviar una petición HTTP sin pasar por el formulario y sus comprobaciones de JavaScript. El servidor debe rechazar igualmente una cantidad o permiso inválidos.','El servidor debe validar cada dato que afecta a sus recursos; el cliente solo mejora la experiencia de uso. Cada petición necesita controles aunque use el formulario.'],
    ['Un documento JSON muy profundo o enorme puede agotar recursos incluso cuando su sintaxis es válida. Un límite de profundidad puede rechazar anidamientos antes de procesarlos completos.','Que el parser acepte el formato no significa que el contenido sea razonable para tu aplicación. Limita documentos antes de procesar entradas externas.']
  ],
  [
    ['Copiar una cadena demasiado larga en un espacio reservado más pequeño puede escribir sobre memoria de otros datos. El resultado puede ser corrupción de datos o un cierre inesperado.','Controla los límites y usa herramientas de detección de errores de memoria durante las pruebas. Comprueba el tamaño del destino antes de copiar.'],
    ['El cálculo de tamaño de una reserva puede desbordarse y producir un valor pequeño para una cantidad de datos grande. Verifica la multiplicación antes de reservar o copiar la memoria.','Comprueba rangos antes de las operaciones y evita asumir que un resultado aritmético siempre cabe en su tipo. Revisa conversiones y cálculos sobre tamaños externos.'],
    ['Al iniciar sesión se verifica la identidad; al abrir un expediente se decide si esa identidad tiene permiso. Una persona autenticada todavía puede tener prohibido consultar ese expediente.','Identificar a una persona y concederle acceso son decisiones distintas: autenticación no sustituye autorización. Verifica identidad y autoriza cada acción por separado.'],
    ['Una solicitud de edición debe comprobar el usuario, el documento concreto, la acción solicitada y las condiciones aplicables. Prueba también el caso de un documento perteneciente a otro usuario.','Un identificador de recurso recibido del cliente no es evidencia de que el usuario pueda utilizarlo. Autoriza en el servidor, no mediante identificadores externos.'],
    ['Una cookie de sesión con HttpOnly no puede leerse directamente usando document.cookie desde JavaScript. El navegador sigue enviando la cookie en las solicitudes permitidas.','HttpOnly limita una vía de robo de cookies, pero un XSS todavía puede realizar acciones dentro de la sesión. Una cookie protegida no vuelve seguro todo el sitio.'],
    ['Una cookie con Secure no debe enviarse por una conexión HTTP ordinaria, sino por un canal HTTPS. Una petición sin HTTPS no debería transportar esa credencial.','Secure protege el envío; no reemplaza HttpOnly, SameSite ni los controles de sesión del servidor. Configura caducidad e invalidación para controlar las sesiones.'],
    ['Un sitio externo puede intentar provocar una operación usando las cookies de una persona autenticada en otro sitio. El servidor debe rechazar la operación si el token no coincide.','Comprueba el token anti-CSRF en operaciones sensibles y define una política SameSite acorde con tus flujos. Evita acciones sensibles activadas mediante enlaces simples.'],
    ['Una API puede permitir que una aplicación web de un origen concreto lea respuestas desde el navegador. Un cliente de línea de comandos todavía puede llamar al endpoint.','CORS no impide que clientes ajenos al navegador llamen a la API: la autorización sigue siendo necesaria. Un origen permitido no sustituye una autorización.'],
    ['Un proceso que pierde referencias a reservas de memoria puede consumir más recursos con cada petición. Observa si el consumo sigue creciendo después de finalizar las peticiones.','Distingue una fuga de un uso legítimo creciente y verifica el consumo bajo cargas prolongadas. Prueba cargas prolongadas, además de ejecuciones breves.'],
    ['Una cookie SameSite puede restringir su envío cuando una petición se origina en un contexto de otro sitio. Prueba navegación, formularios y flujos de inicio de sesión externos.','El comportamiento depende del valor configurado y del contexto; elige la política considerando los flujos legítimos. Los valores SameSite no tienen el mismo comportamiento.']
  ],
  [
    ['Si una entrada se incorpora a una cadena ejecutada por el shell, puede convertirse en parte de una segunda orden. Un separador introducido por el usuario puede alterar la orden original.','No trates comillas o filtros simples como garantía: separa el programa de los datos y limita las operaciones. Prefiere operaciones explícitas y parámetros separados de la instrucción.'],
    ['Una descarga enviada directamente a un intérprete ejecuta lo recibido sin una revisión previa del artefacto completo. Conserva primero el archivo para revisarlo y validar su firma.','Separa descarga, verificación y ejecución para poder comprobar la procedencia y la integridad. El canal de descarga también forma parte de la confianza.'],
    ['Una ruta normalizada puede seguir apuntando fuera de la carpeta de descargas si no se comprueba su destino. Comprueba límites de ruta completos y no únicamente sus primeros caracteres.','No uses una comparación de prefijo ingenua: “/datos-extra” no pertenece a “/datos” aunque empiece igual. Considera enlaces y permisos que puedan cambiar el destino efectivo.'],
    ['Un temporal predecible y compartido puede permitir que otro proceso lea su contenido o prepare un destino inesperado. Un proceso distinto no debería leer los secretos del temporal.','Usa mecanismos de creación segura, permisos mínimos y límites de vida y tamaño. La limpieza debe limitarse a los archivos creados por tu proceso.'],
    ['TLS permite proteger la conexión entre el navegador y el servidor al verificar correctamente el certificado. Un certificado no confiable debe impedir considerar verificada esa conexión.','Un canal protegido puede transportar una petición maliciosa: la aplicación aún debe validar y autorizar. TLS no decide qué puede hacer cada usuario autenticado.'],
    ['El nombre de un instalador no prueba quién lo publicó; verifica el origen y la evidencia de integridad esperada. Una descarga modificada debería fallar la comprobación antes de ejecutarse.','La cadena de confianza incluye el artefacto y el canal por el que obtienes sus hashes, firmas o claves. No obtengas el hash esperado del mismo origen no confiable.'],
    ['Un servicio que procesa archivos no debería poder modificar configuraciones del sistema si su tarea no lo necesita. Así el incidente no concede automáticamente control sobre todo el equipo.','Limitar permisos reduce lo que un atacante puede hacer después de comprometer ese proceso. Revisa permisos de archivos, procesos, cuentas y servicios asociados.'],
    ['Permitir un nombre ya existente puede sobrescribir un archivo ajeno aunque el contenido cargado sea válido. Generar identificadores propios puede evitar colisiones con nombres elegidos externamente.','Controla el nombre, el destino, los permisos y el comportamiento ante colisiones; son comprobaciones separadas. No conviertas directamente un nombre externo en una ruta confiable.'],
    ['Una API de mantenimiento puede permitir solo “generar reporte” y “consultar estado”, sin aceptar órdenes libres. Cada operación puede definir parámetros y permisos específicos para su función.','Una lista de operaciones de negocio es más fácil de controlar que una interfaz a todos los comandos del sistema. Autoriza la operación y sus argumentos como decisiones separadas.'],
    ['Si la verificación de un paquete falla, continuar la instalación elimina la protección que aportaba la firma. Registra el fallo y evita ejecutar el componente mientras se investiga.','Un fallo de verificación debe detener el uso del artefacto y permitir investigar su procedencia. No desactives la verificación para resolver un error de instalación.']
  ],
  [
    ['Un valor insertado en texto HTML y otro insertado dentro de un atributo necesitan tratamiento acorde con su contexto. Un valor de atributo debe permanecer como dato dentro del atributo.','La validación de entrada no reemplaza la codificación de salida; controla dónde y cómo se inserta cada dato. Escapa cerca de la salida usando el contexto correcto.'],
    ['Un comentario persistido con contenido ejecutable puede afectar a cada persona que lo consulte después. Otro visitante puede ejecutar ese contenido al abrir el comentario.','El origen persistente no vuelve confiable el dato: también debes protegerlo al mostrarlo. Protege tanto las entradas almacenadas como su representación posterior.'],
    ['Un error público puede mostrar un identificador de soporte mientras el diagnóstico detallado se guarda en un canal protegido. El soporte puede localizar el diagnóstico usando el identificador público.','Da al usuario información útil sin exponer consultas, rutas, secretos ni detalles internos innecesarios. Separa la información para usuarios de los detalles operativos.'],
    ['Un evento de acceso denegado es más útil si identifica el actor, el recurso, la hora y el resultado. Un identificador de correlación puede relacionar eventos de la misma solicitud.','La trazabilidad debe permitir reconstruir el evento sin convertir los logs en un almacén de secretos. Registra resultados y actores con tiempos consistentes y acceso restringido.'],
    ['Una entrada con saltos de línea puede aparentar que el log contiene un evento adicional que nunca ocurrió. El visor debe mostrar esos caracteres dentro del campo original.','Usa campos estructurados y tratamiento seguro de los datos para preservar el significado de cada evento. Evita que una entrada pueda aparentar otro evento independiente.'],
    ['Registrar un token de sesión completo puede permitir reutilizarlo a quien tenga acceso a ese registro. Un reporte compartido podría convertir esa filtración en una sesión robada.','Revisa también logs de depuración, excepciones y sistemas de monitoreo: pueden capturar secretos accidentalmente. Enmascarar no siempre basta: excluye secretos que no necesitas.'],
    ['Para medir fallos de autenticación normalmente no hace falta registrar el contenido completo del formulario de acceso. Un contador por resultado puede satisfacer esa necesidad sin guardar contraseñas.','Define un propósito, limita los campos recopilados y establece acceso y retención apropiados. Recopila únicamente lo necesario para una finalidad claramente definida.'],
    ['No encontrar un registro puede ser un resultado esperado; una conexión caída puede requerir un manejo de error diferente. El primero puede devolver ausencia; el segundo requiere una respuesta controlada.','El diseño determina qué es excepcional, pero ningún camino de fallo debe ignorarse o filtrar información sensible. No ocultes un fallo devolviendo éxito o resultados ambiguos.'],
    ['Si no es posible verificar un permiso, continuar la operación puede conceder acceso sin una decisión válida. El cliente recibe una denegación y el evento queda registrado.','Deniega de forma controlada cuando la autorización falla y registra la información necesaria para investigar. Fallar de forma segura incluye no revelar información interna.'],
    ['Una CSP puede limitar ciertos scripts mientras la codificación contextual evita interpretar datos como código. Si aparece un defecto, otras capas pueden limitar su explotación.','Las capas complementarias reducen riesgos, pero no convierten una salida HTML insegura en una implementación correcta. Mantén codificación, sanitización y políticas como controles complementarios verificados.']
  ],
  [
    ['Un análisis estático puede señalar concatenaciones peligrosas o accesos inseguros a memoria antes de desplegar la aplicación. El equipo revisa la ubicación y confirma si la entrada es controlable.','Revisa los hallazgos con contexto: una alerta no demuestra por sí sola una explotación y la ausencia de alertas no prueba seguridad. Combina herramientas con revisión de lógica y pruebas dinámicas.'],
    ['Una prueba dinámica envía peticiones al servicio desplegado y observa sus respuestas sin necesitar todo su código fuente. Prueba sesiones distintas para detectar accesos que deberían estar bloqueados.','La cobertura depende de las rutas y estados ejercitados, incluyendo autenticación y distintos permisos. Una ruta no explorada puede mantener defectos sin detectar.'],
    ['Tras corregir un acceso indebido, conserva una prueba que vuelva a intentar esa operación en cada cambio posterior. Si alguien elimina el control, esa prueba debe volver a fallar.','Una prueba de regresión debe verificar la propiedad que falló y evitar que el defecto reaparezca. Incluye el escenario original y variantes relevantes del defecto.'],
    ['Un fuzzer modifica archivos de entrada para buscar cierres inesperados, errores de memoria o comportamientos anómalos. Una entrada que provoca un cierre se conserva para investigar.','Combina exploración de entradas con detección de fallos y conserva los casos que permiten reproducirlos. Reproducir y minimizar el caso facilita encontrar su causa.'],
    ['Ejecutar una línea no demuestra que se hayan probado entradas inválidas o todas sus decisiones de autorización. Dos valores pueden recorrer la misma línea y producir riesgos distintos.','La cobertura orienta la búsqueda de zonas sin probar; no mide directamente la seguridad del sistema. Comprueba condiciones, límites y resultados además de líneas ejecutadas.'],
    ['Una ejecución instrumentada con AddressSanitizer puede detectar un acceso fuera de límites durante una prueba. El reporte señala la operación y ayuda a reconstruir el acceso inválido.','El detector necesita que se ejecute el camino afectado: combina instrumentación con pruebas que lo ejerciten. Instrumentar no reemplaza probar entradas que alcancen caminos vulnerables.'],
    ['Una revisión humana puede detectar que un usuario accede a pedidos ajenos aunque el código no tenga errores de sintaxis. La revisión puede exigir comprobar el dueño en cada consulta.','Busca supuestos de confianza y reglas de negocio, además de patrones técnicos conocidos. Pregunta qué suposiciones dejarían de ser ciertas bajo un ataque.'],
    ['Un archivo válido inicial ayuda a un fuzzer a alcanzar partes del parser que no se exploran con datos totalmente arbitrarios. Las mutaciones pueden mantener suficiente estructura para avanzar dentro del parser.','Diversificar semillas puede ampliar los estados explorados; conserva formatos relevantes para el objetivo. Incluye semillas representativas y casos límite del formato probado.'],
    ['Un reporte útil incluye la versión afectada, la entrada exacta, los pasos y el resultado observado. Otra persona debería poder repetirlo sin adivinar pasos importantes.','Incluye evidencia suficiente para repetir el fallo sin exponer credenciales ni datos reales innecesarios. Distingue claramente el resultado esperado del resultado realmente observado.'],
    ['Un programa puede permitir pruebas en una API concreta, pero excluir infraestructura ajena o acciones que interrumpan el servicio. El investigador confirma esos límites antes de enviar pruebas al servicio.','El alcance y las reglas definen qué pruebas están autorizadas y cómo comunicar los hallazgos. Comunica hallazgos por el canal y proceso previamente definidos.']
  ],
  [
    ['En un DFD, “validar pedido” puede ser un proceso que recibe datos de una entidad y consulta un almacén. También indica qué datos salen y qué almacenes se consultan.','Proceso, entidad externa, almacén y flujo son elementos diferentes: identifica qué hace cada uno con la información. No confundas un proceso lógico con un equipo físico.'],
    ['Al pasar una entrada desde un navegador al servidor se cruza un límite con distintas suposiciones de confianza. El servidor valida lo recibido antes de usarlo en una operación.','Un dato que atraviesa una frontera necesita controles acordes con el nuevo contexto; su procedencia importa. Revisa cada cruce y no únicamente el perímetro externo.'],
    ['Utilizar una identidad robada para hacerse pasar por otra persona corresponde a spoofing. Un servicio puede exigir una prueba de identidad verificable.','Relaciona la suplantación con autenticación y verificación del origen; no la confundas con manipulación de datos. Relaciona cada amenaza con la propiedad que intenta vulnerar.'],
    ['Modificar un pedido o alterar un binario sin autorización corresponde a tampering. Comparar evidencia de integridad ayuda a descubrir modificaciones no esperadas.','Integridad, autorización y detección de cambios ayudan a tratar la manipulación. La protección debe alcanzar datos almacenados y datos en tránsito.'],
    ['Una persona niega haber aprobado una operación y el sistema carece de evidencia confiable que permita investigarla. Una aprobación registrada de forma protegida ayuda a reconstruir lo ocurrido.','Auditoría protegida y mecanismos de firma pueden aportar evidencia, según cómo se gestione la confianza. Protege también el acceso y la integridad de la auditoría.'],
    ['Una cuenta puede obtener funciones administrativas; también puede intentar acceder a recursos de otra cuenta del mismo nivel. Cambiar un identificador puede permitir consultar recursos de otra cuenta.','Distingue escalada vertical de acceso horizontal indebido y verifica ambos tipos de autorización. Comprueba límites entre roles y separación entre usuarios iguales.'],
    ['Un flujo de pagos crítico puede merecer atención antes que una amenaza poco probable sobre una función secundaria. El equipo selecciona mitigaciones que reduzcan ese escenario de mayor impacto.','Prioriza con el impacto, la probabilidad y los controles viables; documenta también los supuestos. Actualiza prioridades si cambian el sistema o sus supuestos.'],
    ['Un diagrama revela dónde llegan datos externos, dónde se almacenan secretos y qué comunicaciones cruzan límites de confianza. Un flujo olvidado puede revelar una vía de entrada no protegida.','La utilidad del DFD está en permitir preguntas sobre los datos y controles, no en su complejidad visual. Mantén el diagrama coherente con el sistema que realmente existe.'],
    ['Muchas solicitudes costosas pueden consumir los recursos disponibles e impedir el acceso de usuarios legítimos. Limitar costes por petición puede reducir el impacto de ese abuso.','Evalúa límites de recursos y recuperación; la disponibilidad también puede verse afectada por entradas válidas pero abusivas. Considera agotamiento de conexiones, memoria, CPU y almacenamiento disponible.'],
    ['Una amenaza identificada puede vincularse con una mitigación, un responsable y una prueba que confirme su funcionamiento. La prueba debe demostrar que el escenario queda bloqueado o limitado.','Un modelo útil produce decisiones y verificaciones; el diagrama es un medio para llegar a ellas. Revisa el modelo cuando cambian flujos, componentes o privilegios.']
  ],
  [
    ['Un resumen permite comparar el contenido recibido con el esperado; su fiabilidad depende del algoritmo y de la referencia de confianza. Un hash publicado por un atacante no acredita el contenido legítimo.','Un hash no cifra ni autentica por sí solo; distingue preimagen, segunda preimagen y colisiones. Para autenticar, necesitas un mecanismo adicional y confianza adecuada.'],
    ['Un atacante que logra dos archivos con el mismo MD5 puede engañar un control que dependa de distinguirlos por ese resumen. Ambos archivos pueden pasar una comparación basada únicamente en ese MD5.','No bases integridad adversarial ni firmas en MD5; revisa el algoritmo y el protocolo completos. La idoneidad depende del uso y del adversario considerado.'],
    ['Dos partes pueden compartir una clave para cifrado simétrico; una firma asimétrica utiliza claves privadas y públicas relacionadas. La clave privada firma y la pública permite verificar esa firma.','Elige el mecanismo según la operación: cifrado, intercambio de claves y firma tienen objetivos diferentes. No intercambies los conceptos de firma y cifrado asimétrico.'],
    ['AES puede formar parte de un esquema de cifrado que también define un modo de operación y su gestión de nonces o IV. Ese esquema debe detectar modificaciones además de ocultar el contenido.','Nombrar un algoritmo robusto no basta: el modo, la autenticación y la gestión de parámetros también importan. Reutilizar parámetros indebidamente puede debilitar un esquema aparentemente sólido.'],
    ['Una clave de 256 bits ocupa 32 bytes; su tamaño describe el espacio ideal, no una cantidad de archivos cifrables. Una clave predecible reduce mucho ese espacio efectivo de búsqueda.','La entropía real, la protección de la clave y la implementación afectan la seguridad más allá del número de bits. Genera claves con suficiente entropía y protégelas durante su vida.'],
    ['Un receptor verifica una firma con la clave pública correspondiente y detecta cambios en el contenido firmado. Si cambia el documento, la verificación ya no debería ser válida.','Verifica también a quién pertenece la clave y su confianza; una firma no oculta el mensaje. Confirma el firmante esperado y qué contenido quedó realmente firmado.'],
    ['Un token de recuperación debe resultar impredecible para quien conoce tokens anteriores o parte del estado del sistema. Un atacante no debería deducir el siguiente token a partir del anterior.','Usa una fuente de aleatoriedad criptográfica para secretos; Math.random no está diseñado para ese propósito. Aleatoriedad para interfaces y aleatoriedad para secretos tienen requisitos distintos.'],
    ['Aunque el cifrado sea sólido, una clave publicada en el repositorio puede permitir acceso a los datos protegidos. Revocar la clave expuesta y reemplazarla limita su uso posterior.','Controla generación, almacenamiento, acceso, rotación y revocación; no evalúes la criptografía solo por el algoritmo. Planifica respuesta a filtraciones antes de que suceda una exposición.'],
    ['Un investigador comunica el hallazgo por el canal acordado y coordina la publicación de detalles con la corrección. La coordinación permite preparar parches y comunicar mitigaciones a los usuarios.','Documenta el impacto y sigue el proceso de comunicación definido para reducir exposición durante la respuesta. Comparte evidencia suficiente evitando datos que faciliten daños innecesarios.'],
    ['Un release puede incluir artefactos verificados, configuración revisada, monitoreo y un plan probado de reversión. Un cambio defectuoso debe poder revertirse sin improvisar todo el procedimiento.','La seguridad continúa en la operación: una construcción segura puede desplegarse de forma insegura. Verifica artefactos y configuración antes y después del despliegue.']
  ]
].flat();
let current=0, selected=null, checked=false, answers={};
function shuffleOptions(){
  return questions.map(q=>{
    const order=q.options.map((_,index)=>index);
    for(let i=order.length-1;i>0;i--){
      const j=Math.floor(Math.random()*(i+1));
      [order[i],order[j]]=[order[j],order[i]];
    }
    return order;
  });
}
let optionOrder=shuffleOptions();
function saveOptionOrder(){
  try { localStorage.setItem('lfd121_option_order',JSON.stringify(optionOrder)); }
  catch(error) { /* El orden se conserva durante esta sesión. */ }
}
function loadOptionOrder(){
  try {
    const saved=JSON.parse(localStorage.getItem('lfd121_option_order')||'null');
    if(Array.isArray(saved)){
      questions.forEach((q,index)=>{
        const order=saved[index];
        if(Array.isArray(order) && order.length===q.options.length && new Set(order).size===order.length && order.every(value=>Number.isInteger(value) && value>=0 && value<q.options.length)){
          optionOrder[index]=order;
        }
      });
    }
  } catch(error) { /* Un orden inválido se reemplaza por uno nuevo. */ }
  saveOptionOrder();
}
function loadAnswers(){
  try {
    const saved=JSON.parse(localStorage.getItem('lfd121_answers')||'{}');
    if(!saved || typeof saved!=='object' || Array.isArray(saved)) return;
    Object.entries(saved).forEach(([key,value])=>{
      const index=Number(key);
      if(String(index)===key && Number.isInteger(index) && index>=0 && index<questions.length && Number.isInteger(value) && value>=0 && value<questions[index].options.length){
        answers[index]=value;
      }
    });
  } catch(error) {
    // Un progreso inválido o almacenamiento bloqueado no impide practicar.
  }
}
function saveAnswers(){
  try { localStorage.setItem('lfd121_answers',JSON.stringify(answers)); }
  catch(error) { /* La práctica continúa aunque no pueda guardarse. */ }
}
function clearAnswers(){
  try { localStorage.removeItem('lfd121_answers'); }
  catch(error) { /* El progreso de esta sesión ya se ha reiniciado. */ }
}
loadAnswers();
loadOptionOrder();
// Los enlaces del manual llevan directamente al concepto que se quiere practicar.
if(typeof location!=='undefined'){
  const requestedQuestion=Number(new URLSearchParams(location.search).get('question'));
  if(Number.isInteger(requestedQuestion) && requestedQuestion>=1 && requestedQuestion<=questions.length){
    current=requestedQuestion-1;
  }
}
selected=answers[current]!==undefined ? answers[current] : null;
checked=answers[current]!==undefined;
const $=s=>document.querySelector(s);
const grid=$('#dayGrid'); days.forEach((d,i)=>grid.insertAdjacentHTML('beforeend',`<article class="day-card" data-day="${i}"><div class="day-no">${String(i+1).padStart(2,'0')}</div><div><h3>${d[0]}</h3><p>${d[1]}</p><div class="mini-progress"><i id="mini${i}"></i></div></div><div class="day-count"><b id="count${i}">0/10</b><br>preguntas</div></article>`));
function feedbackElement(parent,tag,className,text){
  const element=document.createElement(tag);
  element.className=className;
  element.textContent=text;
  parent.appendChild(element);
  return element;
}
function renderFeedback(q,order){
  const panel=$('#explanation');
  const content=$('#feedbackContent');
  content.replaceChildren();
  panel.className='explanation '+(checked?(selected===q.answer?'correct':'incorrect'):'pending');
  if(!checked){
    feedbackElement(content,'p','feedback-empty','Selecciona una opción y pulsa “Comprobar respuesta”. Aquí encontrarás la explicación, un ejemplo práctico y una idea clave para recordar.');
    return;
  }
  feedbackElement(content,'p','feedback-status',selected===q.answer?'Respuesta correcta':'Revisa tu respuesta');
  const answerSection=feedbackElement(content,'section','feedback-section','');
  feedbackElement(answerSection,'h4','','Respuesta correcta');
  const correctLetter=String.fromCharCode(65+order.indexOf(q.answer));
  feedbackElement(answerSection,'p','feedback-answer',correctLetter+'. '+q.options[q.answer]).lang=q.language;
  if(selected!==q.answer){
    const selectedLetter=String.fromCharCode(65+order.indexOf(selected));
    const choice=feedbackElement(answerSection,'p','feedback-choice','Tu elección: ');
    feedbackElement(choice,'span','',selectedLetter+'. '+q.options[selected]).lang=q.language;
  }
  const notes=feedbackNotes[current];
  [['Por qué es correcta',q.explain],['Ejemplo práctico',notes[0]],['Qué debes recordar',notes[1]]].forEach(([title,text],index)=>{
    const section=feedbackElement(content,'section','feedback-section'+(index===2?' feedback-tip':''),'');
    feedbackElement(section,'h4','',title);
    feedbackElement(section,'p','',text);
  });
  const reading=feedbackElement(content,'p','feedback-reading','');
  const link=feedbackElement(reading,'a','','Repasar este concepto en la documentación →');
  link.href='docs.html#concepto-'+(current+1);
}
function render(){
  const q=questions[current];
  const order=optionOrder[current];
  $('#quizTitle').textContent=days[q.day][0];
  $('#quizDay').textContent=`DÍA ${q.day+1} · ${days[q.day][2].toUpperCase()}`;
  $('#quizDifficulty').textContent=q.difficulty;
  $('#questionText').textContent=q.text;
  $('#questionText').lang=q.language;
  $('#questionCounter').textContent=`Pregunta ${current+1} de ${questions.length}`;
  $('#quizProgress').style.width=`${((current+1)/questions.length)*100}%`;
  // value conserva el índice original; A/B/C/D solo indican la posición visible.
  $('#options').innerHTML=order.map((index,position)=>`<label lang="${q.language}" class="option ${selected===index?'selected':''} ${checked?(index===q.answer?'correct':selected===index?'wrong':''):''}"><input type="radio" name="answer" value="${index}" ${selected===index?'checked':''} ${checked?'disabled':''}>${String.fromCharCode(65+position)}. ${q.options[index]}</label>`).join('');
  renderFeedback(q,order);
  $('#nextBtn').textContent=checked?(current===questions.length-1?'Finalizar':'Siguiente pregunta'):'Comprobar respuesta';
  document.querySelectorAll('.option input').forEach(input=>input.onchange=()=>{
    if(checked)return;
    selected=Number(input.value);
    document.querySelectorAll('.option').forEach(label=>label.classList.toggle('selected',Number(label.querySelector('input').value)===selected));
  });
  updateStats();
}
function updateStats(){let entries=Object.entries(answers),correct=entries.filter(([key,value])=>value===questions[Number(key)].answer).length;$('#answeredStat').textContent=entries.length;$('#scoreStat').textContent=entries.length?Math.round(correct/entries.length*100)+'%':'—';days.forEach((_,d)=>{let n=questions.filter((q,i)=>q.day===d&&answers[i]!==undefined).length;$('#count'+d).textContent=n+'/10';$('#mini'+d).style.width=n*10+'%'});}
function go(n){current=Math.max(0,Math.min(99,n));selected=answers[current]!==undefined ? answers[current] : null;checked=answers[current]!==undefined;render();document.querySelector('#practicePanel').scrollIntoView({behavior:'smooth',block:'start'})}
$('#nextBtn').onclick=()=>{if(!checked){if(selected===null)return;answers[current]=selected;saveAnswers();checked=true;render()}else{go(current===questions.length-1?0:current+1)}};$('#prevBtn').onclick=()=>go(current-1);$('#startBtn').onclick=()=>go(current);document.querySelectorAll('.day-card,[data-day]').forEach(el=>el.onclick=()=>go(+el.dataset.day*10));$('#resetBtn').onclick=()=>{if(confirm('¿Reiniciar todas las respuestas?')){answers={};clearAnswers();optionOrder=shuffleOptions();saveOptionOrder();go(0)}};$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');document.querySelectorAll('.view-toggle button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.classList.toggle('compact',b.dataset.view==='compact')});render();
